### PR TITLE
Feature/support oauth2 authentication

### PR DESCRIPTION
**Pull request by s7clarke10**
This feature introduces additional authentication options that weren't possible with just headers in the request (specifically OAuth).

The Meltano sdk supports a number of authentication method which have been supported with this feature. The feature utilizes the available SDK Authenticators https://github.com/meltano/sdk/blob/main/singer_sdk/authenticators.py.

There are many forms of Authentication supported by this feature. By default for legacy support, you can still pass Authentication via headers it should have no breaking changes as part of this feature. If you want to use the built in support for Authentication, this tap supports :

- Basic Authentication
- API Key
- Bearer Token
- OAuth

Please note that OAuthJWTAuthentication has not been developed.

It should be noted that while the Authenticators normally go in the stream.py, I have implemented this in the tap.py because we need the Authenticator to discover the schema which is part of the tap.py logic. The authentication has also just been applied at the top-level, it has not be applied as a individual stream by stream form of authentication.

Finally Note: This branch was built on top of the previous feature "Feature/support_link_list_pagination_tokens" so include the logic for this feature which introduced support for HATEOAS/FHIR API request/reponse styles. There is a previous PR which included this.

Cheers
Steve

### CODE REVIEW

**Comment by jlloyd-widen** [comment]
@s7clarke10 can you think of anyway to setup unit tests for these auth items? I'm thinking of creating a new `tests/test_auth.py` and doing it there.

**Comment by s7clarke10** [comment]
Hi Josh,

Yes the tests for the auth are challenging in that we really need some reliable public domain resource to test the various auth methods against. All my data sources were private end-points so I couldn’t use them for any generic tests.

I am aware of some FHIR Public Server and did a bit of a google. It looks like there are a few with different authentication mechanisms including OAuth2 - https://confluence.hl7.org/display/FHIR/Public+Test+Servers .

I wonder if that might be helpful. Being a public server however it is probably subject to change.

 

There maybe some other examples for different types of API’s like FHIR out there as well.

 

Cheers
Steve

**Comment by s7clarke10** [comment]
Hi Josh,

 

Just touching base with you regard the Pull Request https://github.com/Widen/tap-rest-api-msdk/pull/23 which was built onto of pull request https://github.com/Widen/tap-rest-api-msdk/pull/22 .

 

How are you going with my Pull Request, I was quite keen to get the changes out for the wider community as I can see a lot of benefits being able to support multiple forms of authentication and other request / response types.

 

Thanks
Steve

 

From: ***@***.*** ***@***.***> 
Sent: Wednesday, 17 August 2022 1:12 PM
To: 'Widen/tap-rest-api-msdk' ***@***.***>; 'Widen/tap-rest-api-msdk' ***@***.***>
Cc: 'Mention' ***@***.***>
Subject: RE: [Widen/tap-rest-api-msdk] Feature/support oauth2 authentication (PR #23)

 

Hi Josh,

Yes the tests for the auth are challenging in that we really need some reliable public domain resource to test the various auth methods against. All my data sources were private end-points so I couldn’t use them for any generic tests.

I am aware of some FHIR Public Server and did a bit of a google. It looks like there are a few with different authentication mechanisms including OAuth2 - https://confluence.hl7.org/display/FHIR/Public+Test+Servers .

I wonder if that might be helpful. Being a public server however it is probably subject to change.

 

There maybe some other examples for different types of API’s like FHIR out there as well.

 

Cheers
Steve

**Comment by s7clarke10** [comment]
Hi Josh,

Thanks for the update. Yeah, like you no doubt I’m really struggling for time at the moment. I’m working on four other taps which haven’t been performing that great over the WAN.

I’ll let you know if I do have a chance to look at the tests.

I had to use the tap for a new FHIR API recently which was setup to expect a X-API-KEY and OAuth authentication too. I was pleased that when the X-API-KEY was placed in the header parameter and the rest of the authentication parameters were setup for OAuth it worked well and didn’t require any code changes.

Cheers
Steve

**Comment by s7clarke10** [comment]
Closed: This logic is now incorporated in this PR - https://github.com/Widen/tap-rest-api-msdk/pull/35

**Comment by s7clarke10** [comment]
Closed: This logic is now incorporated in this PR - https://github.com/Widen/tap-rest-api-msdk/pull/36

**Pull request closed without merging**
